"""create constraint for author

Revision ID: 01c474eeecc0
Revises: fadb3e9ad4b4
Create Date: 2024-02-02 21:58:30.766614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c474eeecc0'
down_revision: Union[str, None] = 'fadb3e9ad4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['name', 'birth_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
