"""change in store table

Revision ID: fadb3e9ad4b4
Revises: bc530c68fa4e
Create Date: 2024-02-02 19:57:59.262177

"""
from sqlalchemy.dialects import postgresql
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.store.models import OperationTypeEnum


# revision identifiers, used by Alembic.
revision: str = "fadb3e9ad4b4"
down_revision: Union[str, None] = "bc530c68fa4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    OperationTypeEnum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "storing",
        sa.Column(
            "operation_type",
            sa.Enum("add", "remove", name="operationtype"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    OperationType.drop(op.get_bind(), checkfirst=True)
    op.drop_column("storing", "operation_type")
    # ### end Alembic commands ###
